name: Docker Image CI

on:
  push:
    branches: [ master ]
      
env:
  docker_registry: docker.pkg.github.com/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install buildx
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -L https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        docker buildx version
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name jeedom-docker-builder --driver docker-container --use
    - uses: actions/checkout@v2
    - name: Build & Publish the Docker images
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u $GITHUB_ACTOR docker.pkg.github.com --password-stdin
        docker buildx build --platform $platform --file backup/Dockerfile --tag $backup_image --push --cache-from=$backup_cache_config --cache-to=$backup_cache_config backup/
        docker buildx build --platform $platform --file jeedom-core#stable/Dockerfile --tag $server_image --push --cache-from=$server_cache_config --cache-to=$server_cache_config jeedom-core#stable/
      env:
        backup_image: ${{ env.docker_registry }}/jeedom_backup_multiarch:latest
        server_image: ${{ env.docker_registry }}/jeedom_server_multiarch:latest
        platform: linux/arm
        backup_cache_config: type=registry,ref=${{ env.docker_registry }}/jeedom_backup_multiarch:cache
        server_cache_config: type=registry,ref=${{ env.docker_registry }}/jeedom_server_multiarch:cache

